# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\HTTP\Git\bilive-black\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(220, 170)
        dialog.setMinimumSize(QtCore.QSize(220, 170))
        dialog.setMaximumSize(QtCore.QSize(220, 170))
        self.lineEdit_u = QtWidgets.QLineEdit(dialog)
        self.lineEdit_u.setGeometry(QtCore.QRect(10, 30, 200, 30))
        self.lineEdit_u.setMaxLength(40)
        self.lineEdit_u.setObjectName("lineEdit_u")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 200, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 200, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_p = QtWidgets.QLineEdit(dialog)
        self.lineEdit_p.setGeometry(QtCore.QRect(10, 90, 200, 30))
        self.lineEdit_p.setMaxLength(40)
        self.lineEdit_p.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 130, 200, 30))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "用户登录"))
        self.label.setText(_translate("dialog", "用户名/手机号"))
        self.label_2.setText(_translate("dialog", "密码"))
        self.pushButton.setText(_translate("dialog", "登录"))
